In [2]:
import numpy as np

#### Create numpy array from Python list

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

#### convert type

In [4]:
np.array([1,2,3,4,5], dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [5]:
a2 = np.array([[1,2,3,4], [5,6,7,8]])

In [6]:
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
a2.ndim

2

In [9]:
a2.shape

(2, 4)

In [10]:
a2.dtype

dtype('int32')

In [11]:
a2.size

8

# 1. Create Numpy Arrays from Scratch

#### Zeros, ones, full, arange, linspace

In [12]:
# zeros tạo mảng toàn số không
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.zeros([2,4]).dtype

dtype('float64')

In [14]:
np.zeros([2,4], dtype = 'int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
# np.ones() tạo mảng toàn số 1
np.ones([3,5], dtype = 'float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# np.arange
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
#np.full
np.full([3,5], 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [18]:
# np.linspace linear space
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### Random

In [19]:
# np.random
np.random.random([4,4])

array([[0.09576458, 0.91899699, 0.68151948, 0.59570539],
       [0.94787403, 0.51191409, 0.90462192, 0.60211196],
       [0.52980339, 0.49691239, 0.11673914, 0.6591843 ],
       [0.73262539, 0.61403866, 0.15110465, 0.07618704]])

In [20]:
np.random.random([4,4])

array([[0.42570159, 0.15956198, 0.13711127, 0.2592033 ],
       [0.87780597, 0.48837998, 0.76068956, 0.27900513],
       [0.82595162, 0.75602618, 0.94833714, 0.13282234],
       [0.54695983, 0.24820338, 0.51053204, 0.10103394]])

In [21]:
# Seed
np.random.seed(0)

In [23]:
np.random.random([4,4])

array([[0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369]])

In [25]:
np.random.normal(0,1, [3,3])

array([[-1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794]])

In [26]:
np.random.randint(0, 10, [4,5])

array([[9, 4, 4, 6, 4],
       [4, 3, 4, 4, 8],
       [4, 3, 7, 5, 5],
       [0, 1, 5, 9, 3]])

# 2. Array indexing and slicing

#### One-dimensional subarray

In [27]:
x1 = np.random.randint(0, 20, size = 6)

In [28]:
print(x1)

[ 0  5  0 17 18  4]


#### Multi-dimensional subarray

In [29]:
x2 = np.random.randint(10, size = [3,4])

In [30]:
print(x2)

[[2 0 3 2]
 [0 7 5 9]
 [0 2 7 2]]


# 3. Reshaping of Array & Transpose

In [4]:
grip = np.arange(1, 10)

In [5]:
grip.shape

(9,)

In [6]:
grip

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
grip.reshape([3,3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
x = np.array([1,2,3])
x.shape

(3,)

In [11]:
x = x.reshape([1,3])

In [12]:
x.shape

(1, 3)

In [15]:
x = np.array([[1,2,3], [5,8,13]])
x.shape

(2, 3)

In [16]:
x

array([[ 1,  2,  3],
       [ 5,  8, 13]])

In [17]:
x.T

array([[ 1,  5],
       [ 2,  8],
       [ 3, 13]])

# 4. Array concatenation and Splitting

#### Concatenation

In [18]:
x = np.array([5,8,13])

In [19]:
y = np.array([1,2,3])

In [21]:
np.concatenate([x, y])

array([ 5,  8, 13,  1,  2,  3])

In [22]:
grid = np.array([[1,2,3], [5,8,13]])

In [23]:
grid

array([[ 1,  2,  3],
       [ 5,  8, 13]])

In [24]:
np.concatenate([grid, grid])

array([[ 1,  2,  3],
       [ 5,  8, 13],
       [ 1,  2,  3],
       [ 5,  8, 13]])

In [25]:
np.concatenate([grid, grid], axis = 1)

array([[ 1,  2,  3,  1,  2,  3],
       [ 5,  8, 13,  5,  8, 13]])

In [26]:
x = np.array([1,2,3])
grid = np.array([[5,8,13], [21,34,55]])

In [27]:
y = np.vstack([x, grid])

In [28]:
y

array([[ 1,  2,  3],
       [ 5,  8, 13],
       [21, 34, 55]])

In [32]:
z = np.array([[1],[2]])
y = np.hstack([z, grid])

In [33]:
y

array([[ 1,  5,  8, 13],
       [ 2, 21, 34, 55]])

#### Splitting

In [34]:
x = np.array([1,2,3,5,8,13])

In [35]:
np.split(x, [3,5])

[array([1, 2, 3]), array([5, 8]), array([13])]

In [36]:
x1, x2, x3 = np.split(x, [3,5])

In [37]:
print(x1, x2, x3)

[1 2 3] [5 8] [13]


# 5. Broadcasting and Vectorized operations 


![Alt text](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png "a title")

In [38]:
a = np.arange(3)
a

array([0, 1, 2])

In [39]:
a + 5

array([5, 6, 7])

In [41]:
b = np.ones([3,3])
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [44]:
c = np.arange(3).reshape([3,1])
c

array([[0],
       [1],
       [2]])

In [45]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# 6. Manipulating and Comparing Arrays


![Alt text](https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41586-020-2649-2/MediaObjects/41586_2020_2649_Fig1_HTML.png "a title")

### Aggregation
Aggregation = performing the same operation on a number of things

In [46]:
list_number = [1,2,3,4]
ll = np.array(list_number)

In [47]:
sum(ll)

10

In [48]:
np.sum(ll)

10

In [ ]:
# Create a massive Numpy array
